zones:
  DMZ:
    state: absent
  Client:
     state: absent
#    interfaces:
#      - {"interface_name": "vlan_62"}
#  Server:
#    interfaces:
#      - {"interface_name": "PROD-IMPEX1"}
  
  
addresses:
  auto_import: ^1[0-9][0-9][0-9]$
  import:
    - ESOS-AC-T-FW01
  addresses:
    UAG2:
       interface: "vlan_1065"
       ip: 10.10.0.0/24
       color: 14
  address_groups:
    foobar:
       members: 
         - "UAG2"
#         - foo
       description: foobar
       color: 13

routing:
  static:
    "1":
      address: "10.0.0.10/24"
      gateway: 10.10.10.10
      interface: "vlan_1065"
      metric: 15
      status: enable
      description: "test"
    "2":
      address: "0.0.0.0/0"
      blackhole: enable

application:
  groups:
    'MS-Active directory':
      applications:
         - SSH

cert: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIUWdQWiS96nTOulzQ7kCSj3tRnLXMwDQYJKoZIhvcNAQEN
  BQAwFjEUMBIGA1UEAwwLRWFzeS1SU0EgQ0EwHhcNMjIwOTIyMTExOTA0WhcNMzIw
  OTE5MTExOTA0WjAWMRQwEgYDVQQDDAtFYXN5LVJTQSBDQTCCASIwDQYJKoZIhvcN
  AQEBBQADggEPADCCAQoCggEBANqlK3DIUB9AWw1S40afvEYKXovXCc6HsBwjzRue
  m5fX+huX2vLJQ6I4hi7/ZZs76PQioDYQiSoqoofJeTuTseNRjg44NuQgim++oi3K
  D9ndoVYlte9mJQBgiIhPkKETAXjY0ggUBi2LmtTIODXWn2Wfw/zSEnU9TQulxpDN
  loPwgQhERsjLHov4lRC+sNTlIiAr/nNZSOwYHC2XnxXjLlYvZRInDwMJkaaKi5OM
  nPSrwcUgoxjPwiANaJn9LT8FRSuHcaLsvJ0vbQE66mtC2dfow4p2WVpFPQWEpMiT
  Vy3RZw4gQQRtTHKlqtPmzPUAn4yspqeBiBfcJhLEq4wdpqUCAwEAAaOBkDCBjTAd
  BgNVHQ4EFgQUPZ+ZeaRl6mhJXyN/eMDMZ+BZ/xIwUQYDVR0jBEowSIAUPZ+ZeaRl
  6mhJXyN/eMDMZ+BZ/xKhGqQYMBYxFDASBgNVBAMMC0Vhc3ktUlNBIENBghRZ1BaJ
  L3qdM66XNDuQJKPe1GctczAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkq
  hkiG9w0BAQ0FAAOCAQEAIw12qPce4JrJ7Uw7xcExxz50UDkukwp7MqPgdSH7pWTj
  e/pMLO8MGrAntCCyrt+QsI5wmUT31zNayl+33DfMfiJ+5Lji62GywIiQWNhQqlXZ
  M9znh3iIPK01uVIDbarKsXQLRLVqUnXeJTHiO25fHar8mo8vsUcO3E3gL9yZZrd1
  H/Wfm47GIqWfETx9OLtsCpqnTAupzZvJmDXwYfwAn6Rb3I0ZOtHLxYZfolDXPWYD
  ecxg2L7nHXDmVaBWqx7X21s5ikMy5oJRDHfp5FNMgg9BmHIvAe7ggVJdb1l1FmtS
  MxqLP1IB6Ie12CL099GhndNnY9YPts73/M7UY/oFZQ==
  -----END CERTIFICATE-----

