- name: Configure etcd
  template:
    src: etcd.conf.j2
    dest: /etc/default/etcd
  notify: Restart etcd

- name: Enable and start etcd
  systemd:
    name: etcd
    enabled: yes
    state: started

