- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy HAProxy Configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root


