- name: Install required packages
  apt:
    name:
      - "postgresql-{{ pg_version }}"
      - etcd-server
      - etcd-client
      - patroni
      - haproxy
      - ufw
    state: present
    update_cache: yes

